$(document).ready(function(){
	var shadowbox_conf = {
		animate: true,
		animateFade: true,
		animSequence: "sync",
		modal: false,
		showOverlay: true,
		overlayColor: "#000",
		overlayOpacity: "0.8",
		flashBgColor: "#000000",
		autoplayMovies: true,
		showMovieControls: true,
		slideshowDelay: 0,
		resizeDuration: "0.35",
		fadeDuration: "0.35",
		displayNav: true,
		continuous: false,
		displayCounter: true,
		counterType: "default",
		counterLimit: "10",
		viewportPadding: "20",
		handleOversize: "resize",
		handleUnsupported: "link",
		autoDimensions: false,
		initialHeight: "160",
		initialWidth: "320",
		enableKeys: true,
		skipSetup: false,
		useSizzle: false,
		flashParams: {bgcolor:"#000000", allowFullScreen:true},
		flashVars: {},
		flashVersion: "9.0.0"
	};
	Shadowbox.init(shadowbox_conf);
});
